return {
  "nvim-telescope/telescope.nvim",
  dependencies = {
    "aaronhallaert/advanced-git-search.nvim",
  },
  config = function()
    require("telescope").load_extension("advanced_git_search")
  end,
  keys = {
    -- disable default keybinds
    { "<leader><space>", vim.NIL },
    { "<leader>,", vim.NIL },
    { "<leader>sa", vim.NIL },
    { "<leader>sb", vim.NIL },
    { "<leader>sc", vim.NIL },
    { "<leader>sC", vim.NIL },
    { "<leader>sd", vim.NIL },
    { "<leader>sg", vim.NIL },
    { "<leader>sG", vim.NIL },
    { "<leader>sh", vim.NIL },
    { "<leader>sH", vim.NIL },
    { "<leader>sk", vim.NIL },
    { "<leader>sM", vim.NIL },
    { "<leader>sm", vim.NIL },
    { "<leader>so", vim.NIL },
    { "<leader>sR", vim.NIL },
    { "<leader>sw", vim.NIL },
    { "<leader>sW", vim.NIL },
    { "<leader>ss", vim.NIL },
    { "<leader>sS", vim.NIL },
    -- find
    { "<leader>f<space>", "<cmd>Telescope resume<cr>", desc = "Resume" },
    { "<leader>fa", "<cmd>Telescope autocommands<cr>", desc = "Auto Commands" },
    { "<leader>fc", "<cmd>Telescope command_history<cr>", desc = "Command History" },
    { "<leader>fC", "<cmd>Telescope commands<cr>", desc = "Commands" },
    { "<leader>fd", "<cmd>Telescope diagnostics<cr>", desc = "Diagnostics" },
    { "<leader>fg", LazyVim.pick("live_grep"), desc = "Grep (Root Dir)" },
    { "<leader>fG", LazyVim.pick("live_grep", { root = false }), desc = "Grep (cwd)" },
    { "<leader>fh", "<cmd>Telescope help_tags<cr>", desc = "Help Pages" },
    { "<leader>fH", "<cmd>Telescope highlights<cr>", desc = "Search Highlight Groups" },
    { "<leader>fk", "<cmd>Telescope keymaps<cr>", desc = "Key Maps" },
    { "<leader>fM", "<cmd>Telescope man_pages<cr>", desc = "Man Pages" },
    { "<leader>fm", "<cmd>Telescope marks<cr>", desc = "Jump to Mark" },
    { "<leader>fo", "<cmd>Telescope vim_options<cr>", desc = "Options" },
    { "<leader>fw", LazyVim.pick("grep_string"), desc = "Word (root dir)" },
    { "<leader>fW", LazyVim.pick("grep_string", { root = false }), desc = "Word (cwd)" },
    {
      "<leader>fs",
      LazyVim.pick("lsp_document_symbols", {
        symbols = {
          "Class",
          "Function",
          "Method",
          "Constructor",
          "Interface",
          "Module",
          "Struct",
          "Trait",
          "Field",
          "Property",
        },
      }),
      desc = "Goto Symbol",
    },
    {
      "<leader>fS",
      LazyVim.pick("lsp_workspace_symbols", {
        symbols = {
          "Class",
          "Function",
          "Method",
          "Constructor",
          "Interface",
          "Module",
          "Struct",
          "Trait",
          "Field",
          "Property",
        },
      }),
      desc = "Goto Symbol (Workspace)",
    },
  },
}
